name: app-build-android-only

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: '输入编译的分支名 (例如 master)'
        required: false
        default: 'master'

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: 签出代码
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag_name || github.ref_name }}

      - name: 设置 JAVA 环境
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: "17"
          cache: 'gradle'

      - name: 设置 Flutter 环境
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: 更新依赖
        run: flutter pub get

      - name: 打包 Android 调试版 (适配 6.0 TV)
        # --debug 会使用系统默认签名，跳过密钥要求
        # --target-platform android-arm 专门针对老旧电视的 v7a 架构
        run: flutter build apk --debug --target-platform android-arm

      - name: 上传 APK 产物
        uses: actions/upload-artifact@v4
        with:
          name: android-tv-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
          retention-days: 1
